# Generated by Django 5.2.10 on 2026-01-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=10, help_text='Pojemność (liczba osób)'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Lokalizacja, np. piętro, budynek', max_length=255),
        ),
    ]
